# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5b40cba66efcdad256f2bc1dbe590d064bb70978ac609fbeacac91822bb6ae5336d77215729c94a267c615032f95a551f4c1f51ed476eb839780ca1d93c3f2c

test:
  secret_key_base: bd8d49a8603c4a5ada917730eee3bd361c84e353a5e51c551b9c734555582fa5b36b75644c9db7f117d2cc7f0e5f3239f87d98efc7dde5b322679490a60b919a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
